### ISSUE TITLE
TODO : Finish instructions (jump, ret, call, bit etc)

### ISSUE THREAD

**Issue by abastie** [corentingay/gistreboy#15]

**Comment by ashleygay** [comment]
- Instruction that starts with CB are on 16bits
- the last 8 bits are telling us what the instruction is and what it is doing
- Example:
        * CB_44 is BIT 0,H
        * CB_7C is BIT 7,H
        * In this case to increment the left arg by one, we add 8 to the opcode
- Another example
        * CB_45 is BIT 0,L
